FROM zendexpressive

# Make vim available for debugging purposes
RUN apt-get update \
    && apt-get install -y vim

# Copy over a default route configuration
# This is based on the existing one generated by the Zend Expressive Skeleton Installer
# Plus some sample routes
COPY ./docker/routes.php /var/www/html/config/routes.php

# Copy Composer as it's required for Zend Expressive Tooling
COPY ./docker/composer /usr/local/bin/composer
